// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package testproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageV1 struct {
	Field1               string   `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2               int64    `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageV1) Reset()         { *m = MessageV1{} }
func (m *MessageV1) String() string { return proto.CompactTextString(m) }
func (*MessageV1) ProtoMessage()    {}
func (*MessageV1) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e_v1, []int{0}
}

func (m *MessageV1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageV1.Unmarshal(m, b)
}
func (m *MessageV1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageV1.Marshal(b, m, deterministic)
}
func (m *MessageV1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageV1.Merge(m, src)
}
func (m *MessageV1) XXX_Size() int {
	return xxx_messageInfo_MessageV1.Size(m)
}
func (m *MessageV1) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageV1.DiscardUnknown(m)
}

var xxx_messageInfo_MessageV1 proto.InternalMessageInfo

func (m *MessageV1) GetField1() string {
	if m != nil {
		return m.Field1
	}
	return ""
}

func (m *MessageV1) GetField2() int64 {
	if m != nil {
		return m.Field2
	}
	return 0
}

func init() {
	proto.RegisterType((*MessageV1)(nil), "testproto.MessageV1")
}

func init() {
	proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e_v1)
}

var fileDescriptor_c161fcfdc0c3ff1e_v1 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0x25, 0x6b, 0x2e, 0x4e,
	0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0xd4, 0x30, 0x43, 0x21, 0x31, 0x2e, 0xb6, 0xb4, 0xcc, 0xd4,
	0x9c, 0x14, 0x43, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x28, 0x0f, 0x2e, 0x6e, 0x24, 0xc1,
	0xa4, 0xc0, 0xa8, 0xc1, 0x0c, 0x15, 0x37, 0x72, 0x32, 0x88, 0xd2, 0x4b, 0xcf, 0x2c, 0xc9, 0x28,
	0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0x2e, 0x29, 0x4a, 0x2d, 0x49, 0xce, 0x28, 0xd2, 0x07,
	0x99, 0x9e, 0x99, 0x56, 0xa9, 0x9f, 0x99, 0x57, 0x92, 0x5a, 0x94, 0x97, 0x98, 0xa3, 0x0f, 0xb7,
	0x2e, 0x89, 0x0d, 0x4c, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xea, 0x4f, 0xb3, 0x47, 0x8e,
	0x00, 0x00, 0x00,
}
