// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/golang/mock/sample/captor (interfaces: Dao)

// Package mock_captor is a generated GoMock package.
package mock_captor

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDao is a mock of Dao interface
type MockDao struct {
	ctrl     *gomock.Controller
	recorder *MockDaoMockRecorder
}

// MockDaoMockRecorder is the mock recorder for MockDao
type MockDaoMockRecorder struct {
	mock *MockDao
}

// NewMockDao creates a new mock instance
func NewMockDao(ctrl *gomock.Controller) *MockDao {
	mock := &MockDao{ctrl: ctrl}
	mock.recorder = &MockDaoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDao) EXPECT() *MockDaoMockRecorder {
	return m.recorder
}

// InsertIDs mocks base method
func (m *MockDao) InsertIDs(arg0 []int) {
	m.ctrl.Call(m, "InsertIDs", arg0)
}

// InsertIDs indicates an expected call of InsertIDs
func (mr *MockDaoMockRecorder) InsertIDs(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertIDs", reflect.TypeOf((*MockDao)(nil).InsertIDs), arg0)
}
