// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route_guide.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	route_guide.proto

It has these top-level messages:
	Point
	Rectangle
	Feature
	RouteNote
	RouteSummary
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Points are represented as latitude-longitude pairs in the E7 representation
// (degrees multiplied by 10**7 and rounded to the nearest integer).
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
type Point struct {
	Latitude  int32 `protobuf:"varint,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude int32 `protobuf:"varint,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Point) GetLatitude() int32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() int32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

// A latitude-longitude rectangle, represented as two diagonally opposite
// points "lo" and "hi".
type Rectangle struct {
	// One corner of the rectangle.
	Lo *Point `protobuf:"bytes,1,opt,name=lo" json:"lo,omitempty"`
	// The other corner of the rectangle.
	Hi *Point `protobuf:"bytes,2,opt,name=hi" json:"hi,omitempty"`
}

func (m *Rectangle) Reset()                    { *m = Rectangle{} }
func (m *Rectangle) String() string            { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()               {}
func (*Rectangle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Rectangle) GetLo() *Point {
	if m != nil {
		return m.Lo
	}
	return nil
}

func (m *Rectangle) GetHi() *Point {
	if m != nil {
		return m.Hi
	}
	return nil
}

// A feature names something at a given point.
//
// If a feature could not be named, the name is empty.
type Feature struct {
	// The name of the feature.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The point where the feature is detected.
	Location *Point `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

// A RouteNote is a message sent while at a given point.
type RouteNote struct {
	// The location from which the message is sent.
	Location *Point `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	// The message to be sent.
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *RouteNote) Reset()                    { *m = RouteNote{} }
func (m *RouteNote) String() string            { return proto.CompactTextString(m) }
func (*RouteNote) ProtoMessage()               {}
func (*RouteNote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RouteNote) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RouteNote) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// A RouteSummary is received in response to a RecordRoute rpc.
//
// It contains the number of individual points received, the number of
// detected features, and the total distance covered as the cumulative sum of
// the distance between each point.
type RouteSummary struct {
	// The number of points received.
	PointCount int32 `protobuf:"varint,1,opt,name=point_count,json=pointCount" json:"point_count,omitempty"`
	// The number of known features passed while traversing the route.
	FeatureCount int32 `protobuf:"varint,2,opt,name=feature_count,json=featureCount" json:"feature_count,omitempty"`
	// The distance covered in metres.
	Distance int32 `protobuf:"varint,3,opt,name=distance" json:"distance,omitempty"`
	// The duration of the traversal in seconds.
	ElapsedTime int32 `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime" json:"elapsed_time,omitempty"`
}

func (m *RouteSummary) Reset()                    { *m = RouteSummary{} }
func (m *RouteSummary) String() string            { return proto.CompactTextString(m) }
func (*RouteSummary) ProtoMessage()               {}
func (*RouteSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RouteSummary) GetPointCount() int32 {
	if m != nil {
		return m.PointCount
	}
	return 0
}

func (m *RouteSummary) GetFeatureCount() int32 {
	if m != nil {
		return m.FeatureCount
	}
	return 0
}

func (m *RouteSummary) GetDistance() int32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *RouteSummary) GetElapsedTime() int32 {
	if m != nil {
		return m.ElapsedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "grpc.Point")
	proto.RegisterType((*Rectangle)(nil), "grpc.Rectangle")
	proto.RegisterType((*Feature)(nil), "grpc.Feature")
	proto.RegisterType((*RouteNote)(nil), "grpc.RouteNote")
	proto.RegisterType((*RouteSummary)(nil), "grpc.RouteSummary")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for RouteGuide service

type RouteGuideClient interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(ctx context.Context, in *Point, opts ...grpc1.CallOption) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc1.CallOption) (RouteGuide_ListFeaturesClient, error)
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(ctx context.Context, opts ...grpc1.CallOption) (RouteGuide_RecordRouteClient, error)
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(ctx context.Context, opts ...grpc1.CallOption) (RouteGuide_RouteChatClient, error)
}

type routeGuideClient struct {
	cc *grpc1.ClientConn
}

func NewRouteGuideClient(cc *grpc1.ClientConn) RouteGuideClient {
	return &routeGuideClient{cc}
}

func (c *routeGuideClient) GetFeature(ctx context.Context, in *Point, opts ...grpc1.CallOption) (*Feature, error) {
	out := new(Feature)
	err := grpc1.Invoke(ctx, "/grpc.RouteGuide/GetFeature", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeGuideClient) ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc1.CallOption) (RouteGuide_ListFeaturesClient, error) {
	stream, err := grpc1.NewClientStream(ctx, &_RouteGuide_serviceDesc.Streams[0], c.cc, "/grpc.RouteGuide/ListFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideListFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RouteGuide_ListFeaturesClient interface {
	Recv() (*Feature, error)
	grpc1.ClientStream
}

type routeGuideListFeaturesClient struct {
	grpc1.ClientStream
}

func (x *routeGuideListFeaturesClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeGuideClient) RecordRoute(ctx context.Context, opts ...grpc1.CallOption) (RouteGuide_RecordRouteClient, error) {
	stream, err := grpc1.NewClientStream(ctx, &_RouteGuide_serviceDesc.Streams[1], c.cc, "/grpc.RouteGuide/RecordRoute", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideRecordRouteClient{stream}
	return x, nil
}

type RouteGuide_RecordRouteClient interface {
	Send(*Point) error
	CloseAndRecv() (*RouteSummary, error)
	grpc1.ClientStream
}

type routeGuideRecordRouteClient struct {
	grpc1.ClientStream
}

func (x *routeGuideRecordRouteClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeGuideRecordRouteClient) CloseAndRecv() (*RouteSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RouteSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeGuideClient) RouteChat(ctx context.Context, opts ...grpc1.CallOption) (RouteGuide_RouteChatClient, error) {
	stream, err := grpc1.NewClientStream(ctx, &_RouteGuide_serviceDesc.Streams[2], c.cc, "/grpc.RouteGuide/RouteChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeGuideRouteChatClient{stream}
	return x, nil
}

type RouteGuide_RouteChatClient interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc1.ClientStream
}

type routeGuideRouteChatClient struct {
	grpc1.ClientStream
}

func (x *routeGuideRouteChatClient) Send(m *RouteNote) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeGuideRouteChatClient) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RouteGuide service

type RouteGuideServer interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(context.Context, *Point) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(*Rectangle, RouteGuide_ListFeaturesServer) error
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(RouteGuide_RecordRouteServer) error
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(RouteGuide_RouteChatServer) error
}

func RegisterRouteGuideServer(s *grpc1.Server, srv RouteGuideServer) {
	s.RegisterService(&_RouteGuide_serviceDesc, srv)
}

func _RouteGuide_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteGuideServer).GetFeature(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.RouteGuide/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteGuideServer).GetFeature(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteGuide_ListFeatures_Handler(srv interface{}, stream grpc1.ServerStream) error {
	m := new(Rectangle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteGuideServer).ListFeatures(m, &routeGuideListFeaturesServer{stream})
}

type RouteGuide_ListFeaturesServer interface {
	Send(*Feature) error
	grpc1.ServerStream
}

type routeGuideListFeaturesServer struct {
	grpc1.ServerStream
}

func (x *routeGuideListFeaturesServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _RouteGuide_RecordRoute_Handler(srv interface{}, stream grpc1.ServerStream) error {
	return srv.(RouteGuideServer).RecordRoute(&routeGuideRecordRouteServer{stream})
}

type RouteGuide_RecordRouteServer interface {
	SendAndClose(*RouteSummary) error
	Recv() (*Point, error)
	grpc1.ServerStream
}

type routeGuideRecordRouteServer struct {
	grpc1.ServerStream
}

func (x *routeGuideRecordRouteServer) SendAndClose(m *RouteSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeGuideRecordRouteServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RouteGuide_RouteChat_Handler(srv interface{}, stream grpc1.ServerStream) error {
	return srv.(RouteGuideServer).RouteChat(&routeGuideRouteChatServer{stream})
}

type RouteGuide_RouteChatServer interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc1.ServerStream
}

type routeGuideRouteChatServer struct {
	grpc1.ServerStream
}

func (x *routeGuideRouteChatServer) Send(m *RouteNote) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeGuideRouteChatServer) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RouteGuide_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.RouteGuide",
	HandlerType: (*RouteGuideServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "GetFeature",
			Handler:    _RouteGuide_GetFeature_Handler,
		},
	},
	Streams: []grpc1.StreamDesc{
		{
			StreamName:    "ListFeatures",
			Handler:       _RouteGuide_ListFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecordRoute",
			Handler:       _RouteGuide_RecordRoute_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RouteChat",
			Handler:       _RouteGuide_RouteChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "route_guide.proto",
}

func init() { proto.RegisterFile("route_guide.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x5e, 0x97, 0x2e, 0xdb, 0x4c, 0xb2, 0x5a, 0x31, 0xa7, 0x28, 0x8b, 0x04, 0x84, 0x03, 0x2b,
	0x0e, 0x51, 0x95, 0x7d, 0x02, 0xb6, 0xa2, 0xbd, 0xa0, 0xaa, 0x0a, 0xdc, 0x2b, 0x93, 0x0c, 0xa9,
	0x25, 0x27, 0x8e, 0x12, 0x47, 0x82, 0xe7, 0xe0, 0xd9, 0x78, 0x1f, 0x64, 0x3b, 0x49, 0x7f, 0x40,
	0x7b, 0xf3, 0x7c, 0xdf, 0x7c, 0x33, 0x9e, 0x6f, 0x06, 0x5e, 0xb5, 0xaa, 0xd7, 0xb4, 0x2f, 0x7b,
	0x51, 0x50, 0xd2, 0xb4, 0x4a, 0x2b, 0x9c, 0x97, 0x6d, 0x93, 0xc7, 0x9f, 0xe0, 0x7a, 0xa7, 0x44,
	0xad, 0x31, 0x82, 0x85, 0xe4, 0x5a, 0xe8, 0xbe, 0xa0, 0x90, 0xbd, 0x65, 0x0f, 0xd7, 0xd9, 0x14,
	0xe3, 0x6b, 0xf0, 0xa4, 0xaa, 0x4b, 0x47, 0xce, 0x2c, 0x79, 0x04, 0xe2, 0xcf, 0xe0, 0x65, 0x94,
	0x6b, 0x5e, 0x97, 0x92, 0xf0, 0x1e, 0x66, 0x52, 0xd9, 0x02, 0x7e, 0xea, 0x27, 0xa6, 0x45, 0x62,
	0xeb, 0x67, 0x33, 0xa9, 0x0c, 0x79, 0x10, 0xb6, 0xc0, 0x25, 0x79, 0x10, 0xf1, 0x1a, 0x6e, 0xd6,
	0xc4, 0x75, 0xdf, 0x12, 0x22, 0xcc, 0x6b, 0x5e, 0xb9, 0x7f, 0x78, 0x99, 0x7d, 0xe3, 0x07, 0x58,
	0x48, 0x95, 0x73, 0x2d, 0x54, 0xfd, 0xbf, 0x0a, 0x13, 0x19, 0x6f, 0xc1, 0xcb, 0xcc, 0xb0, 0x5b,
	0xa5, 0xcf, 0x55, 0xec, 0x19, 0x15, 0x86, 0x70, 0x53, 0x51, 0xd7, 0xf1, 0xd2, 0x0d, 0xe8, 0x65,
	0x63, 0x18, 0xff, 0x66, 0x10, 0xd8, 0x82, 0x5f, 0xfb, 0xaa, 0xe2, 0xed, 0x2f, 0x7c, 0x03, 0x7e,
	0x63, 0xd4, 0xfb, 0x5c, 0xf5, 0xb5, 0x1e, 0xcc, 0x02, 0x0b, 0xad, 0x0c, 0x82, 0xef, 0xe1, 0xf6,
	0x87, 0x9b, 0x64, 0x48, 0x71, 0x96, 0x05, 0x03, 0xe8, 0x92, 0x22, 0x58, 0x14, 0xa2, 0xd3, 0xbc,
	0xce, 0x29, 0x7c, 0xe1, 0xfc, 0x1e, 0x63, 0x7c, 0x07, 0x01, 0x49, 0xde, 0x74, 0x54, 0xec, 0xb5,
	0xa8, 0x28, 0x9c, 0x5b, 0xde, 0x1f, 0xb0, 0x6f, 0xa2, 0xa2, 0xf4, 0x0f, 0x03, 0xb0, 0xbf, 0xda,
	0x98, 0x95, 0xe2, 0x47, 0x80, 0x0d, 0xe9, 0xd1, 0xbf, 0xd3, 0x19, 0xa3, 0x5b, 0x17, 0x0c, 0x5c,
	0x7c, 0x85, 0x29, 0x04, 0x5f, 0x44, 0x37, 0x26, 0x77, 0x78, 0xe7, 0x12, 0xa6, 0x1d, 0xfe, 0xa3,
	0x58, 0x32, 0x4c, 0xc1, 0xcf, 0x28, 0x57, 0x6d, 0x61, 0x7b, 0x9e, 0x37, 0xc0, 0x41, 0x7f, 0xe2,
	0x51, 0x7c, 0xf5, 0xc0, 0xf0, 0x71, 0x58, 0xc4, 0xea, 0xc0, 0xf5, 0xd4, 0x64, 0xdc, 0x4c, 0x74,
	0x09, 0x18, 0xc9, 0x92, 0x3d, 0x2d, 0xe1, 0x5e, 0x28, 0x47, 0xd1, 0x4f, 0x5e, 0x35, 0x92, 0xba,
	0xc4, 0xde, 0xae, 0x3d, 0xdd, 0xa7, 0xbb, 0xe3, 0xcc, 0x3b, 0x73, 0xc5, 0x3b, 0xf6, 0xfd, 0xa5,
	0x3d, 0xe7, 0xc7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x64, 0xaf, 0xa5, 0xec, 0xe3, 0x02, 0x00,
	0x00,
}
