// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/banaio/mock/sample/grpc (interfaces: RouteGuideClient,RouteGuide_ListFeaturesClient,RouteGuide_RecordRouteClient,RouteGuide_RouteChatClient)

// Package mock_grpc is a generated GoMock package.
package mock_grpc

import (
	context "context"
	grpc "github.com/banaio/mock/sample/grpc"
	gomock "github.com/golang/mock/gomock"
	grpc0 "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	reflect "reflect"
)

// MockRouteGuideClient is a mock of RouteGuideClient interface
type MockRouteGuideClient struct {
	ctrl     *gomock.Controller
	recorder *MockRouteGuideClientMockRecorder
}

// MockRouteGuideClientMockRecorder is the mock recorder for MockRouteGuideClient
type MockRouteGuideClientMockRecorder struct {
	mock *MockRouteGuideClient
}

// NewMockRouteGuideClient creates a new mock instance
func NewMockRouteGuideClient(ctrl *gomock.Controller) *MockRouteGuideClient {
	mock := &MockRouteGuideClient{ctrl: ctrl}
	mock.recorder = &MockRouteGuideClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRouteGuideClient) EXPECT() *MockRouteGuideClientMockRecorder {
	return m.recorder
}

// GetFeature mocks base method
func (m *MockRouteGuideClient) GetFeature(arg0 context.Context, arg1 *grpc.Point, arg2 ...grpc0.CallOption) (*grpc.Feature, error) {
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFeature", varargs...)
	ret0, _ := ret[0].(*grpc.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeature indicates an expected call of GetFeature
func (mr *MockRouteGuideClientMockRecorder) GetFeature(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeature", reflect.TypeOf((*MockRouteGuideClient)(nil).GetFeature), varargs...)
}

// ListFeatures mocks base method
func (m *MockRouteGuideClient) ListFeatures(arg0 context.Context, arg1 *grpc.Rectangle, arg2 ...grpc0.CallOption) (grpc.RouteGuide_ListFeaturesClient, error) {
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFeatures", varargs...)
	ret0, _ := ret[0].(grpc.RouteGuide_ListFeaturesClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeatures indicates an expected call of ListFeatures
func (mr *MockRouteGuideClientMockRecorder) ListFeatures(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeatures", reflect.TypeOf((*MockRouteGuideClient)(nil).ListFeatures), varargs...)
}

// RecordRoute mocks base method
func (m *MockRouteGuideClient) RecordRoute(arg0 context.Context, arg1 ...grpc0.CallOption) (grpc.RouteGuide_RecordRouteClient, error) {
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RecordRoute", varargs...)
	ret0, _ := ret[0].(grpc.RouteGuide_RecordRouteClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordRoute indicates an expected call of RecordRoute
func (mr *MockRouteGuideClientMockRecorder) RecordRoute(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRoute", reflect.TypeOf((*MockRouteGuideClient)(nil).RecordRoute), varargs...)
}

// RouteChat mocks base method
func (m *MockRouteGuideClient) RouteChat(arg0 context.Context, arg1 ...grpc0.CallOption) (grpc.RouteGuide_RouteChatClient, error) {
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RouteChat", varargs...)
	ret0, _ := ret[0].(grpc.RouteGuide_RouteChatClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RouteChat indicates an expected call of RouteChat
func (mr *MockRouteGuideClientMockRecorder) RouteChat(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteChat", reflect.TypeOf((*MockRouteGuideClient)(nil).RouteChat), varargs...)
}

// MockRouteGuide_ListFeaturesClient is a mock of RouteGuide_ListFeaturesClient interface
type MockRouteGuide_ListFeaturesClient struct {
	ctrl     *gomock.Controller
	recorder *MockRouteGuide_ListFeaturesClientMockRecorder
}

// MockRouteGuide_ListFeaturesClientMockRecorder is the mock recorder for MockRouteGuide_ListFeaturesClient
type MockRouteGuide_ListFeaturesClientMockRecorder struct {
	mock *MockRouteGuide_ListFeaturesClient
}

// NewMockRouteGuide_ListFeaturesClient creates a new mock instance
func NewMockRouteGuide_ListFeaturesClient(ctrl *gomock.Controller) *MockRouteGuide_ListFeaturesClient {
	mock := &MockRouteGuide_ListFeaturesClient{ctrl: ctrl}
	mock.recorder = &MockRouteGuide_ListFeaturesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRouteGuide_ListFeaturesClient) EXPECT() *MockRouteGuide_ListFeaturesClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method
func (m *MockRouteGuide_ListFeaturesClient) CloseSend() error {
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend
func (mr *MockRouteGuide_ListFeaturesClientMockRecorder) CloseSend() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockRouteGuide_ListFeaturesClient)(nil).CloseSend))
}

// Context mocks base method
func (m *MockRouteGuide_ListFeaturesClient) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockRouteGuide_ListFeaturesClientMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockRouteGuide_ListFeaturesClient)(nil).Context))
}

// Header mocks base method
func (m *MockRouteGuide_ListFeaturesClient) Header() (metadata.MD, error) {
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header
func (mr *MockRouteGuide_ListFeaturesClientMockRecorder) Header() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockRouteGuide_ListFeaturesClient)(nil).Header))
}

// Recv mocks base method
func (m *MockRouteGuide_ListFeaturesClient) Recv() (*grpc.Feature, error) {
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*grpc.Feature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv
func (mr *MockRouteGuide_ListFeaturesClientMockRecorder) Recv() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockRouteGuide_ListFeaturesClient)(nil).Recv))
}

// RecvMsg mocks base method
func (m *MockRouteGuide_ListFeaturesClient) RecvMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockRouteGuide_ListFeaturesClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockRouteGuide_ListFeaturesClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method
func (m *MockRouteGuide_ListFeaturesClient) SendMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockRouteGuide_ListFeaturesClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockRouteGuide_ListFeaturesClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method
func (m *MockRouteGuide_ListFeaturesClient) Trailer() metadata.MD {
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer
func (mr *MockRouteGuide_ListFeaturesClientMockRecorder) Trailer() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockRouteGuide_ListFeaturesClient)(nil).Trailer))
}

// MockRouteGuide_RecordRouteClient is a mock of RouteGuide_RecordRouteClient interface
type MockRouteGuide_RecordRouteClient struct {
	ctrl     *gomock.Controller
	recorder *MockRouteGuide_RecordRouteClientMockRecorder
}

// MockRouteGuide_RecordRouteClientMockRecorder is the mock recorder for MockRouteGuide_RecordRouteClient
type MockRouteGuide_RecordRouteClientMockRecorder struct {
	mock *MockRouteGuide_RecordRouteClient
}

// NewMockRouteGuide_RecordRouteClient creates a new mock instance
func NewMockRouteGuide_RecordRouteClient(ctrl *gomock.Controller) *MockRouteGuide_RecordRouteClient {
	mock := &MockRouteGuide_RecordRouteClient{ctrl: ctrl}
	mock.recorder = &MockRouteGuide_RecordRouteClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRouteGuide_RecordRouteClient) EXPECT() *MockRouteGuide_RecordRouteClientMockRecorder {
	return m.recorder
}

// CloseAndRecv mocks base method
func (m *MockRouteGuide_RecordRouteClient) CloseAndRecv() (*grpc.RouteSummary, error) {
	ret := m.ctrl.Call(m, "CloseAndRecv")
	ret0, _ := ret[0].(*grpc.RouteSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseAndRecv indicates an expected call of CloseAndRecv
func (mr *MockRouteGuide_RecordRouteClientMockRecorder) CloseAndRecv() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAndRecv", reflect.TypeOf((*MockRouteGuide_RecordRouteClient)(nil).CloseAndRecv))
}

// CloseSend mocks base method
func (m *MockRouteGuide_RecordRouteClient) CloseSend() error {
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend
func (mr *MockRouteGuide_RecordRouteClientMockRecorder) CloseSend() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockRouteGuide_RecordRouteClient)(nil).CloseSend))
}

// Context mocks base method
func (m *MockRouteGuide_RecordRouteClient) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockRouteGuide_RecordRouteClientMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockRouteGuide_RecordRouteClient)(nil).Context))
}

// Header mocks base method
func (m *MockRouteGuide_RecordRouteClient) Header() (metadata.MD, error) {
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header
func (mr *MockRouteGuide_RecordRouteClientMockRecorder) Header() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockRouteGuide_RecordRouteClient)(nil).Header))
}

// RecvMsg mocks base method
func (m *MockRouteGuide_RecordRouteClient) RecvMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockRouteGuide_RecordRouteClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockRouteGuide_RecordRouteClient)(nil).RecvMsg), arg0)
}

// Send mocks base method
func (m *MockRouteGuide_RecordRouteClient) Send(arg0 *grpc.Point) error {
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockRouteGuide_RecordRouteClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockRouteGuide_RecordRouteClient)(nil).Send), arg0)
}

// SendMsg mocks base method
func (m *MockRouteGuide_RecordRouteClient) SendMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockRouteGuide_RecordRouteClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockRouteGuide_RecordRouteClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method
func (m *MockRouteGuide_RecordRouteClient) Trailer() metadata.MD {
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer
func (mr *MockRouteGuide_RecordRouteClientMockRecorder) Trailer() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockRouteGuide_RecordRouteClient)(nil).Trailer))
}

// MockRouteGuide_RouteChatClient is a mock of RouteGuide_RouteChatClient interface
type MockRouteGuide_RouteChatClient struct {
	ctrl     *gomock.Controller
	recorder *MockRouteGuide_RouteChatClientMockRecorder
}

// MockRouteGuide_RouteChatClientMockRecorder is the mock recorder for MockRouteGuide_RouteChatClient
type MockRouteGuide_RouteChatClientMockRecorder struct {
	mock *MockRouteGuide_RouteChatClient
}

// NewMockRouteGuide_RouteChatClient creates a new mock instance
func NewMockRouteGuide_RouteChatClient(ctrl *gomock.Controller) *MockRouteGuide_RouteChatClient {
	mock := &MockRouteGuide_RouteChatClient{ctrl: ctrl}
	mock.recorder = &MockRouteGuide_RouteChatClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRouteGuide_RouteChatClient) EXPECT() *MockRouteGuide_RouteChatClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method
func (m *MockRouteGuide_RouteChatClient) CloseSend() error {
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend
func (mr *MockRouteGuide_RouteChatClientMockRecorder) CloseSend() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockRouteGuide_RouteChatClient)(nil).CloseSend))
}

// Context mocks base method
func (m *MockRouteGuide_RouteChatClient) Context() context.Context {
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context
func (mr *MockRouteGuide_RouteChatClientMockRecorder) Context() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockRouteGuide_RouteChatClient)(nil).Context))
}

// Header mocks base method
func (m *MockRouteGuide_RouteChatClient) Header() (metadata.MD, error) {
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header
func (mr *MockRouteGuide_RouteChatClientMockRecorder) Header() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockRouteGuide_RouteChatClient)(nil).Header))
}

// Recv mocks base method
func (m *MockRouteGuide_RouteChatClient) Recv() (*grpc.RouteNote, error) {
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*grpc.RouteNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv
func (mr *MockRouteGuide_RouteChatClientMockRecorder) Recv() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockRouteGuide_RouteChatClient)(nil).Recv))
}

// RecvMsg mocks base method
func (m *MockRouteGuide_RouteChatClient) RecvMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg
func (mr *MockRouteGuide_RouteChatClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockRouteGuide_RouteChatClient)(nil).RecvMsg), arg0)
}

// Send mocks base method
func (m *MockRouteGuide_RouteChatClient) Send(arg0 *grpc.RouteNote) error {
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockRouteGuide_RouteChatClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockRouteGuide_RouteChatClient)(nil).Send), arg0)
}

// SendMsg mocks base method
func (m *MockRouteGuide_RouteChatClient) SendMsg(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg
func (mr *MockRouteGuide_RouteChatClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockRouteGuide_RouteChatClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method
func (m *MockRouteGuide_RouteChatClient) Trailer() metadata.MD {
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer
func (mr *MockRouteGuide_RouteChatClientMockRecorder) Trailer() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockRouteGuide_RouteChatClient)(nil).Trailer))
}
