// Code generated by MockGen. DO NOT EDIT.
// Source: input.go

// Package plain_func is a generated GoMock package.
package plain_func

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFunc is a mock of Func interface
type MockFunc struct {
	ctrl     *gomock.Controller
	recorder *MockFuncMockRecorder
}

// MockFuncMockRecorder is the mock recorder for MockFunc
type MockFuncMockRecorder struct {
	mock *MockFunc
}

// NewMockFunc creates a new mock instance
func NewMockFunc(ctrl *gomock.Controller) *MockFunc {
	mock := &MockFunc{ctrl: ctrl}
	mock.recorder = &MockFuncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFunc) EXPECT() *MockFuncMockRecorder {
	return m.recorder
}

// Call mocks base method
func (m *MockFunc) Call(arg0 int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Call indicates an expected call of Call
func (mr *MockFuncMockRecorder) Call(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockFunc)(nil).Call), arg0)
}
