// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/golang/mock/mockgen/tests/stdiogarbage (interfaces: I)

// Package test is a generated GoMock package.
package test

import (
	gomock "github.com/golang/mock/gomock"
)

// MockI is a mock of I interface
type MockI struct {
	ctrl     *gomock.Controller
	recorder *MockIMockRecorder
}

// MockIMockRecorder is the mock recorder for MockI
type MockIMockRecorder struct {
	mock *MockI
}

// NewMockI creates a new mock instance
func NewMockI(ctrl *gomock.Controller) *MockI {
	mock := &MockI{ctrl: ctrl}
	mock.recorder = &MockIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockI) EXPECT() *MockIMockRecorder {
	return m.recorder
}
